/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef USEFUL-CPP-SOURCE_PRIVATE_H
#define USEFUL-CPP-SOURCE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"3.5.0.4"
#define VER_MAJOR	3
#define VER_MINOR	5
#define VER_RELEASE	0
#define VER_BUILD	4
#define COMPANY_NAME	""
#define FILE_VERSION	"3.5.0.4"
#define FILE_DESCRIPTION	"AOCode Useful CPP Source"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"AOCode Useful CPP Source"
#define PRODUCT_VERSION	"3.5.0.4"

#endif /*USEFUL-CPP-SOURCE_PRIVATE_H*/
